services:
  - type: cron
    name: youtube-channel-playlist-agent
    runtime: python
    envVars:
    - fromGroup: youtube-channel-playlist-agent
    schedule: "0 */3 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

