services:
- type: cron
  name: youtube-channel-playlist-agent
  runtime: docker
  repo: https://github.com/gfleetwood/youtube-channel-playlist-agent
  plan: starter
  envVars:
  - fromGroup: youtube-channel-playlist-agent
  region: oregon
  dockerfilePath: ./Dockerfile
  schedule: "0 */12 * * *"